import Foundation

// MARK: - HelpCardPayload

/// Static snapshot of all registered commands/skills/mentions captured at /help time.
/// Carried on a ChatMessage so the card renders without re-querying live registries.
struct HelpCardPayload: Sendable, Equatable {
    let builtInItems: [HelpCardItem]
    let projectSkills: [HelpCardItem]
    let userSkills: [HelpCardItem]
    let mentions: [HelpCardItem]
    let mcpTools: [HelpCardItem]
    let shortcuts: [HelpCardItem]

    struct HelpCardItem: Sendable, Equatable, Identifiable {
        let id: String
        let label: String
        let description: String
    }
}

// MARK: - ChatRole

enum ChatRole: Equatable {
    case user
    case assistant
}

// MARK: - ToolEventStatus

enum ToolEventStatus: String, Codable {
    case pending, running, completed, failed
}

// MARK: - ChatToolEvent

struct ChatToolEvent: Identifiable, Equatable, Codable {
    let id: String
    let name: String
    var status: ToolEventStatus
    let argsPreview: String
    /// Truncated stdout/result string captured from the tool's terminating event.
    /// Bound to 1024 chars upstream in the parser so persisted messages stay small.
    var output: String? = nil
}

// MARK: - ChatMessage

struct ChatMessage: Identifiable, Equatable {
    let id: UUID
    let role: ChatRole
    var content: String
    let timestamp: Date
    var isStreaming: Bool
    var autoInjectedIntent: String? = nil
    var toolEvents: [ChatToolEvent]? = nil
    /// Hidden context attached to a user message (e.g. auto-injected git diff). Sent to model in payload but NOT displayed in bubble. Carried forward to subsequent turns until classifier fires a different intent.
    var internalContext: String? = nil
    /// Structured plan parsed from assistant XML response. Nil until a plan is detected.
    var plan: ChatPlan? = nil
    /// Edit blocks extracted from an assistant message (search-and-replace operations).
    var editBlocks: [EditBlock]? = nil
    /// The CLI provider that generated this message (e.g. "anthropic", "openai"). Nil for API-sourced messages.
    var providerUsed: String? = nil
    /// Non-nil on synthetic assistant messages generated by /help. Drives SlashHelpCard rendering.
    var helpCardPayload: HelpCardPayload? = nil
    /// Files the user attached to this message (images, PDFs). Empty array is
    /// treated as "no attachments" by every render + provider routing path.
    var attachments: [ChatAttachment] = []

    init(
        id: UUID = UUID(),
        role: ChatRole,
        content: String,
        timestamp: Date = Date(),
        isStreaming: Bool = false,
        autoInjectedIntent: String? = nil,
        toolEvents: [ChatToolEvent]? = nil,
        internalContext: String? = nil,
        plan: ChatPlan? = nil,
        editBlocks: [EditBlock]? = nil,
        providerUsed: String? = nil,
        helpCardPayload: HelpCardPayload? = nil,
        attachments: [ChatAttachment] = []
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.isStreaming = isStreaming
        self.autoInjectedIntent = autoInjectedIntent
        self.toolEvents = toolEvents
        self.internalContext = internalContext
        self.plan = plan
        self.editBlocks = editBlocks
        self.providerUsed = providerUsed
        self.helpCardPayload = helpCardPayload
        self.attachments = attachments
    }
}

// MARK: - ChatThread

struct ChatThread: Identifiable, Equatable {
    let id: UUID
    var messages: [ChatMessage]
    let createdAt: Date
    var repoID: String
    var title: String
    /// Captured from the CLI provider's first event of the previous turn so the
    /// next turn can resume the same server-side session
    /// (`claude --resume <id>` / `codex exec resume <id>`).
    /// Provider-specific: cleared whenever the user switches providers.
    var cliSessionID: String? = nil
    var cliSessionProvider: String? = nil
    /// Sum of `total_cost_usd` reported by the CLI on each turn's terminating
    /// event. Codex Plus is unmetered → stays 0.
    var totalCostUSD: Double = 0
    /// Cumulative token usage across all turns of this thread, summed from
    /// every provider that reports it (claude, codex, OpenAI-compatible local).
    var totalInputTokens: Int = 0
    var totalOutputTokens: Int = 0

    init(
        id: UUID = UUID(),
        messages: [ChatMessage] = [],
        createdAt: Date = Date(),
        repoID: String = "",
        title: String = ChatThread.defaultTitle(),
        cliSessionID: String? = nil,
        cliSessionProvider: String? = nil,
        totalCostUSD: Double = 0,
        totalInputTokens: Int = 0,
        totalOutputTokens: Int = 0
    ) {
        self.id = id
        self.messages = messages
        self.createdAt = createdAt
        self.repoID = repoID
        self.title = title
        self.cliSessionID = cliSessionID
        self.cliSessionProvider = cliSessionProvider
        self.totalCostUSD = totalCostUSD
        self.totalInputTokens = totalInputTokens
        self.totalOutputTokens = totalOutputTokens
    }

    static func defaultTitle(date: Date = Date()) -> String {
        String(format: L10n("chat.thread.untitled"), DateFormatter.chatThreadShort.string(from: date))
    }
}

// MARK: - DateFormatter + ChatThread

private extension DateFormatter {
    static let chatThreadShort: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm"
        return formatter
    }()
}

// MARK: - ContinueChipEvent

/// Carries metadata for the "Continue" suggestion chip shown after an assistant turn.
struct ContinueChipEvent: Equatable, Sendable {
    /// The suggested follow-up text to pre-fill in the chat input.
    let suggestedText: String
    /// Hop-score boost applied when ranking this chip against other candidates.
    let hopBoost: Int
}

// MARK: - ChatAttachmentUnsupportedBanner

/// Emitted when the user tries to attach a file whose MIME type is not in
/// `Constants.Attachments.acceptedMIMEs`. Drives an inline banner in the chat UI.
struct ChatAttachmentUnsupportedBanner: Equatable, Sendable {
    /// Original filename the user attempted to attach.
    let filename: String
    /// Detected (or guessed) MIME type, if available.
    let detectedMIME: String?
}
